#!/usr/bin/env bash
#
# Rebuilds assets/ - every file the Issabel 5 web UI would otherwise pull from
# a CDN - and writes assets/SOURCES.txt with where each file came from.
#
# Run this on a machine with internet access, review the diff, commit.
# The PBX itself never needs internet access - install.sh only copies files.
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT
out=$tmp/assets
sources=$tmp/SOURCES.txt

# get <url> <path under assets/>
get() {
  mkdir -p "$(dirname "$out/$2")"
  curl -fsSL -A "$UA" "$1" -o "$out/$2"
  [[ -s $out/$2 ]] || { echo "empty download: $1" >&2; exit 1; }
  if head -c 512 "$out/$2" | grep -qi '<html'; then
    echo "got an HTML page instead of $2: $1" >&2; exit 1
  fi
  printf '%s\t%s\n' "$2" "$1" >> "$sources"
}

# --- Noto Sans (Google Fonts) -------------------------------------------------
# Same family/weights the templates request. A current browser UA makes Google
# answer with woff2 + unicode-range subsets. Files are named after subset and
# style; Google serves 400 and 700 from one variable file, so a weight is only
# appended when a name would otherwise clash.
noto_css='https://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic&display=swap'
mkdir -p "$out/noto-sans"
curl -fsSL -A "$UA" "$noto_css" -o "$tmp/google.css"
awk -v list="$tmp/noto-files.txt" '
  /^\/\* .+ \*\/$/  { subset = $2 }
  /font-style:/     { style = $2;  sub(/;/, "", style) }
  /font-weight:/    { weight = $2; sub(/;/, "", weight) }
  /src: *url\(/ {
    match($0, /url\([^)]*\)/)
    url = substr($0, RSTART + 4, RLENGTH - 5)
    if (!(url in name)) {
      n = "noto-sans-" subset "-" style
      if (n in taken) n = n "-" weight
      taken[n] = 1
      name[url] = n ".woff2"
      print url, name[url] > list
    }
    sub(/url\([^)]*\)/, "url(" name[url] ")")
  }
  { print }
' "$tmp/google.css" > "$tmp/noto-body.css"
{
  echo "/*"
  echo " * Noto Sans 400 / 700 / 400 italic, served locally for Issabel 5."
  echo " * Generated by tools/fetch-assets.sh - do not edit by hand."
  echo " * License: SIL Open Font License 1.1 (see OFL.txt)."
  echo " */"
  cat "$tmp/noto-body.css"
} > "$out/noto-sans/noto-sans.css"
printf '%s\t%s\n' noto-sans/noto-sans.css "$noto_css (rewritten to local file names)" >> "$sources"
while read -r url file; do
  get "$url" "noto-sans/$file"
  [[ $(head -c 4 "$out/noto-sans/$file") == wOF2 ]] || { echo "not woff2: $url" >&2; exit 1; }
done < "$tmp/noto-files.txt"
get https://raw.githubusercontent.com/google/fonts/main/ofl/notosans/OFL.txt noto-sans/OFL.txt

# --- Font Awesome 4.7.0 (IssabelPBX admin) ------------------------------------
# The framework ships Font Awesome 4.4.0, but the admin pages use 4.7.0 icons.
fa=https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0
get "$fa/css/font-awesome.min.css" font-awesome-4.7.0/css/font-awesome.min.css
for font in $(grep -oE "\.\./fonts/[^?#')]+" "$out/font-awesome-4.7.0/css/font-awesome.min.css" | sort -u); do
  get "$fa/${font#../}" "font-awesome-4.7.0/${font#../}"
done

# --- jQuery UI 1.8.9 (IssabelPBX admin, views/issabelpbx.php) -----------------
get https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/jquery-ui.min.js jquery-ui-1.8.9/jquery-ui.min.js

# --- IE-only polyfills in the login templates ---------------------------------
# Not from oss.maxcdn.com: that host now serves a different html5shiv version.
get https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.0/html5shiv.js html5shiv-3.7.0/html5shiv.js
get https://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.min.js respond-1.4.2/respond.min.js
get https://ajax.googleapis.com/ajax/libs/chrome-frame/1/CFInstall.min.js chrome-frame-1/CFInstall.min.js

# --- AmplitudeJS player icons (PBX -> Monitoring) -----------------------------
# 521dimensions.com took these down (404), so they come from the Web Archive.
for icon in play pause; do
  get "https://web.archive.org/web/2020id_/https://521dimensions.com/img/open-source/amplitudejs/examples/single-song/$icon.svg" "amplitudejs/$icon.svg"
  grep -q '<svg' "$out/amplitudejs/$icon.svg" || { echo "not an svg: $icon" >&2; exit 1; }
done

# --- SOURCES.txt --------------------------------------------------------------
{
  echo "# Every file in assets/, its sha256 and where it was downloaded from."
  echo "# Generated by tools/fetch-assets.sh."
  echo
  sort "$sources" | while IFS=$'\t' read -r file url; do
    printf '%s  %s\n    %s\n' "$(sha256sum "$out/$file" | cut -d' ' -f1)" "$file" "$url"
  done
} > "$out/SOURCES.txt"

rm -rf assets
mv "$out" assets
echo "assets/ rebuilt: $(find assets -type f | wc -l) files, $(du -sh assets | cut -f1)"
