#!/usr/bin/env bash
#
# Rebuilds fonts/noto-sans/ from Google Fonts: downloads the woff2 files and
# writes a noto-sans.css that points at them by relative path.
#
# Run this on a machine that can reach Google, then commit the result.
# The PBX itself never needs internet access - install.sh only copies files.
#
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

OUT=fonts/noto-sans
# Same family/weights the Issabel 5 templates request (400, 700, 400 italic).
QUERY='Noto+Sans:400,700,400italic&display=swap'
# A current browser UA makes Google answer with woff2 + unicode-range subsets.
UA='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0.0 Safari/537.36'
LICENSE_URL='https://raw.githubusercontent.com/google/fonts/main/ofl/notosans/OFL.txt'

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

curl -fsSL -A "$UA" "https://fonts.googleapis.com/css?family=${QUERY}" -o "$tmp/google.css"

# Name each file after its subset and style, e.g. noto-sans-latin-italic.woff2.
# Google serves 400 and 700 from one variable file, so two @font-face blocks
# can share a URL; a weight is appended only if a name would otherwise clash.
awk -v list="$tmp/files.txt" '
  /^\/\* .+ \*\/$/  { subset = $2 }
  /font-style:/     { style = $2;  sub(/;/, "", style) }
  /font-weight:/    { weight = $2; sub(/;/, "", weight) }
  /src: *url\(/ {
    match($0, /url\([^)]*\)/)
    url = substr($0, RSTART + 4, RLENGTH - 5)
    if (!(url in name)) {
      n = "noto-sans-" subset "-" style
      if (n in taken) n = n "-" weight
      taken[n] = 1
      name[url] = n ".woff2"
      print url, name[url] > list
    }
    sub(/url\([^)]*\)/, "url(" name[url] ")")
  }
  { print }
' "$tmp/google.css" > "$tmp/body.css"

count=0
while read -r url file; do
  curl -fsSL "$url" -o "$tmp/$file"
  [[ $(head -c 4 "$tmp/$file") == wOF2 ]] || { echo "not a woff2 file: $url" >&2; exit 1; }
  count=$((count + 1))
done < "$tmp/files.txt"

curl -fsSL "$LICENSE_URL" -o "$tmp/OFL.txt"

{
  echo "/*"
  echo " * Noto Sans 400 / 700 / 400 italic, served locally for Issabel 5."
  echo " * Generated by tools/fetch-fonts.sh - do not edit by hand."
  echo " * License: SIL Open Font License 1.1 (see OFL.txt)."
  echo " */"
  cat "$tmp/body.css"
} > "$tmp/noto-sans.css"

rm -f "$OUT"/*.woff2 "$OUT"/noto-sans.css "$OUT"/OFL.txt
mkdir -p "$OUT"
cp "$tmp"/*.woff2 "$tmp/noto-sans.css" "$tmp/OFL.txt" "$OUT"/

echo "Wrote $count font files, noto-sans.css and OFL.txt to $OUT/"
